package com.tim.one.enums

enum MessageType {
	FORGOT_PASSWORD, REGISTER, NEW_USER, FORGOT_USERNAME, MUSICIAN_ASSIGNED_FACILITATOR, MUSICIAN_REFUSED, COMPANY_ASSIGNED_BUYER, COMPANY_REFUSED, MUSICIAN_ASSIGNED_USER, COMPANY_ASSIGNED_USER, COMPANY_EDITED, MUSICIAN_EDITED, CONTACT, MESSAGE, COMPANY_INTEGRATED, USER, CLIENTE, PROVEEDOR
}
